function createfigure(Y1)
%CREATEFIGURE(Y1)
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 16-Oct-2019 15:50:54

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(Y1);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 500]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 200]);
box(axes1,'on');
